import React, { useState } from 'react';
import { DEMO_AUDIT, DEMO_COMPLIANCE, DEMO_ORGANIZATIONS, DEMO_USERS } from '../../../packages/domain/src/demo-data';
import { readLocal, writeLocal } from './local-state';
import { Card, Metric, PageHead, Status } from './ui';

export const Overview = () => <><PageHead eyebrow="Admin / Overview" title="Platform governance" subtitle="Admin is a supporting application for identity, access, compliance and audit. It is not a fourth PiHub business module."/>
<div className="ph-demo">Admin is a supporting application, not a fourth business module. Demo governance data only: real role changes, compliance decisions and session revocation must be server-enforced before production use.</div>
<div className="ph-grid cols-4"><Metric value={DEMO_ORGANIZATIONS.length} label="Organizations"/><Metric value={DEMO_USERS.length} label="Demo users"/><Metric value={DEMO_COMPLIANCE.filter(x=>x.status!=='Verified').length} label="Compliance items open"/><Metric value={DEMO_AUDIT.length} label="Recent audit events"/></div>
<div className="ph-grid cols-2" style={{marginTop:16}}><Card title="Governance priorities"><ul className="ph-list"><li><span>KYB annual review · Berlin Living GmbH</span><Status tone="bad">Action required</Status></li><li><span>UBO evidence · ABC Development AG</span><Status tone="warn">In review</Status></li><li><span>Shared-session backend contract</span><Status>Backend dependency</Status></li></ul></Card><Card title="Architecture boundary"><p className="ph-subtitle">Admin can manage access policy and compliance context, but it must never become a hidden route inside Investor, Borrower or Advisory. It owns its own deployment and authorization surface.</p></Card></div></>;

export const Organizations = () => <><PageHead eyebrow="Admin / Organizations" title="Organizations" subtitle="Manage legal-entity context used across Borrower, Investor and Advisory without creating duplicate organization records."/><div className="ph-table-wrap"><table className="ph-table"><thead><tr><th>Organization</th><th>Type</th><th>Jurisdiction</th><th>Compliance</th><th>Risk</th><th>Users</th></tr></thead><tbody>{DEMO_ORGANIZATIONS.map(o=><tr key={o.id}><td><strong>{o.name}</strong><div className="ph-metric-label">{o.id}</div></td><td>{o.type}</td><td>{o.jurisdiction}</td><td><Status tone={o.compliance==='Verified'?'good':'warn'}>{o.compliance}</Status></td><td>{o.risk}</td><td>{o.users}</td></tr>)}</tbody></table></div></>;

export const Users = () => {
 const [users,setUsers]=useState(()=>readLocal('users',DEMO_USERS));
 const toggle=(id,module)=>{const next=users.map(u=>u.id===id?{...u,modules:u.modules.includes(module)?u.modules.filter(m=>m!==module):[...u.modules,module]}:u);setUsers(next);writeLocal('users',next)};
 return <><PageHead eyebrow="Admin / Identity" title="Users & roles" subtitle="The UI can demonstrate role management, but production authorization must be validated by the server for every module, action and record."/><div className="ph-table-wrap"><table className="ph-table"><thead><tr><th>User</th><th>Organization</th><th>Roles</th><th>Module access</th><th>Demo action</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.name}</strong><div className="ph-metric-label">{u.email}</div></td><td>{u.organization}</td><td>{u.roles.join(', ')}</td><td>{u.modules.join(', ') || 'None'}</td><td><button className="ph-button" onClick={()=>toggle(u.id,'Borrower')}>{u.modules.includes('Borrower')?'Remove Borrower':'Add Borrower'}</button></td></tr>)}</tbody></table></div></>;
};

export const Compliance = () => {
 const [items,setItems]=useState(()=>readLocal('compliance',DEMO_COMPLIANCE));
 const advance=id=>{const next=items.map(i=>i.id===id?{...i,status:i.status==='Verified'?'Verified':'Verified'}:i);setItems(next);writeLocal('compliance',next)};
 return <><PageHead eyebrow="Admin / Compliance" title="Compliance queue" subtitle="KYB, UBO, investor classification and review expiry belong in a dedicated controlled workflow rather than scattered profile fields."/><div className="ph-table-wrap"><table className="ph-table"><thead><tr><th>Organization</th><th>Check</th><th>Status</th><th>Owner</th><th>Due</th><th></th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.organization}</td><td>{i.check}</td><td><Status tone={i.status==='Verified'?'good':i.status==='Action required'?'bad':'warn'}>{i.status}</Status></td><td>{i.owner}</td><td>{i.due}</td><td>{i.status!=='Verified'?<button className="ph-button" onClick={()=>advance(i.id)}>Verify demo</button>:'—'}</td></tr>)}</tbody></table></div></>;
};

export const AccessPolicies = () => <><PageHead eyebrow="Admin / Authorization" title="Access policies" subtitle="Module visibility is not authorization. Production policies must be enforced by the API using user, organization, role, module, action and record scope."/><div className="ph-grid cols-3"><Card title="Borrower"><p className="ph-subtitle">Organization members may access only their borrower-facing financing requests, documents and messages.</p><Status>Server-enforced target</Status></Card><Card title="Investor"><p className="ph-subtitle">Capital-provider users may access only opportunities, positions and documents granted to their institution and role.</p><Status>Server-enforced target</Status></Card><Card title="Advisory"><p className="ph-subtitle">PiHub transaction users may access mandates and work products assigned to their internal scope.</p><Status>Server-enforced target</Status></Card></div><Card title="Admin rule"><div className="ph-callout">Admin can configure policy, but a frontend toggle must never be treated as proof that the policy is secure. The backend remains the authority.</div></Card></>;

export const Audit = () => <><PageHead eyebrow="Admin / Audit" title="Audit log" subtitle="Security, role and transaction-governance events should be immutable server records with actor, time, entity and reason."/><div className="ph-table-wrap"><table className="ph-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th></tr></thead><tbody>{DEMO_AUDIT.map(a=><tr key={a.id}><td>{a.at}</td><td>{a.actor}</td><td>{a.action}</td><td><strong>{a.entity}</strong></td></tr>)}</tbody></table></div></>;

export const Platform = () => <><PageHead eyebrow="Admin / Platform" title="Platform boundaries" subtitle="Operational status for the independently deployable PiHub applications and the backend capabilities they still require."/><div className="ph-grid cols-2"><Card title="Applications"><ul className="ph-list"><li><span>Investor</span><Status tone="good">Production</Status></li><li><span>Borrower</span><Status tone="good">Application implemented</Status></li><li><span>Advisory</span><Status tone="good">Application implemented</Status></li><li><span>Admin</span><Status tone="good">Application implemented</Status></li><li><span>Access</span><Status tone="warn">Gateway only</Status></li></ul></Card><Card title="Backend contracts"><ul className="ph-list"><li><span>Shared secure session / SSO</span><Status tone="bad">Required</Status></li><li><span>Server RBAC / record authorization</span><Status tone="bad">Required</Status></li><li><span>Canonical deal / document APIs</span><Status tone="bad">Required</Status></li><li><span>Audit/event persistence</span><Status tone="bad">Required</Status></li></ul></Card></div></>;
