import { test, expect } from '@playwright/test';
const CENTRAL_LOGIN='https://pihub-investor.vercel.app';
const stubCentralLogin=async page=>page.route(`${CENTRAL_LOGIN}/**`,route=>route.fulfill({status:200,contentType:'text/html',body:'<!doctype html><html><body><h1>Central PiHub sign in</h1></body></html>'}));
const open=page=>page.goto('/?pihub_demo_access=admin&source=investor-access');
const routes=[['Organizations','/organizations','Organizations'],['Users & roles','/users','Users & roles'],['Compliance','/compliance','Compliance queue'],['Access policies','/access-policies','Access policies'],['Audit log','/audit','Audit log'],['Platform','/platform','Platform boundaries']];

test('admin central handoff, Investor design contract and every destination work',async({page})=>{await open(page);await expect(page.locator('.ph-app[data-workspace="admin"]')).toBeVisible();await expect(page).not.toHaveURL(/pihub_demo_access/);if((page.viewportSize()?.width||0)>820){const d=await page.evaluate(()=>{const c=n=>getComputedStyle(n);return{font:c(document.body).fontFamily,top:c(document.querySelector('.ph-topbar')).height,side:c(document.querySelector('.ph-sidebar')).width,bg:c(document.querySelector('.ph-sidebar')).backgroundColor,canvas:c(document.querySelector('.ph-main')).backgroundColor}});expect(d.font).toContain('IBM Plex Sans');expect(d.top).toBe('68px');expect(d.side).toBe('232px');expect(d.bg).toBe('rgb(11, 18, 32)');expect(d.canvas).toBe('rgb(246, 248, 252)')}for(const[link,path,heading]of routes){await page.getByRole('link',{name:link,exact:true}).first().click();await expect(page).toHaveURL(new RegExp(`${path}$`));await expect(page.getByRole('heading',{name:heading})).toBeVisible()}expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(2)});

test('admin user access and compliance actions persist',async({page})=>{await open(page);await page.goto('/users');const action=page.getByRole('button',{name:'Add Borrower'}).first();await action.click();await expect(page.getByRole('button',{name:'Remove Borrower'}).first()).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Remove Borrower'}).first()).toBeVisible();await page.goto('/compliance');await page.getByRole('button',{name:'Verify demo'}).first().click();await expect(page.getByText('Verified',{exact:true}).first()).toBeVisible()});

test('admin has one login surface and sign out returns centrally',async({page})=>{await open(page);await stubCentralLogin(page);await page.getByRole('button',{name:'Sign out'}).click();await expect(page).toHaveURL(`${CENTRAL_LOGIN}/login?next=admin`)});
test('admin direct unauthenticated visit has no fallback login',async({page})=>{await stubCentralLogin(page);await page.goto('/');await expect(page).toHaveURL(`${CENTRAL_LOGIN}/login?next=admin`);await expect(page.getByRole('button',{name:'Open Admin'})).toHaveCount(0)});
