import React,{useEffect,useMemo,useState}from'react';
import{Link,Navigate,NavLink,Route,Routes,useLocation,useNavigate}from'react-router-dom-v6';
import{clearDemoSession,consumeDemoAccessHandoff,readDemoSession,redirectToCentralAccess}from'../../../packages/platform/src/demo-session';
import{DEMO_DEAL}from'../../../packages/domain/src/demo-data';
import WorkspaceAccount from'../../../packages/ui/src/WorkspaceAccount';
import{APP_ID,APP_LABEL,DEMO_ACCOUNT}from'./config';import Overview from'./Overview';import{Mandates,Transactions,Structuring,Counterparties,DueDiligence,Execution,Tasks}from'./pages';
const NAV=[{label:'Workspace',items:[['Overview','/','overview']]},{label:'Pipeline',items:[['Mandates','/mandates','mandates'],['Transactions','/transactions','transactions']]},{label:'Execution',items:[['Structuring','/structuring','structuring'],['Counterparties','/counterparties','counterparties'],['Due diligence','/due-diligence','dd'],['Execution','/execution','execution'],['Tasks','/tasks','tasks']]}];
const Icon=({name})=><span className="ph-nav-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d={name==='overview'?'M4 13h6V4H4v9m10 7h6v-9h-6v9':name==='transactions'?'M4 7h16M7 4L4 7l3 3M20 17H4m13-3 3 3-3 3':name==='mandates'?'M6 3h12v18H6zM9 7h6M9 11h6M9 15h4':name==='dd'?'M5 4h14v16H5zM8 8h8M8 12h5M8 16h3':name==='execution'?'M4 12l5 5L20 6M4 18h12':name==='tasks'?'M5 5h14v14H5zM8 9l2 2 3-4M14 10h3':name==='structuring'?'M4 6h16M7 6v12M17 6v12M4 18h16':'M4 20a8 8 0 0 1 16 0M8 8a4 4 0 1 0 8 0'}/></svg></span>;
const Redirect=()=>{useEffect(()=>{redirectToCentralAccess(APP_ID)},[]);return null};
const Workspace=({session,onLogout})=>{const location=useLocation(),navigate=useNavigate(),items=useMemo(()=>NAV.flatMap(s=>s.items),[]);const link=i=><NavLink key={i[1]} to={i[1]} end={i[1]==='/'} className={({isActive})=>`ph-nav-link${isActive?' active':''}`}><Icon name={i[2]}/><span>{i[0]}</span></NavLink>;return <div className="ph-app" data-workspace="advisory"><header className="ph-topbar"><div className="ph-topbar-leading"><button className="ph-brand" type="button" onClick={()=>navigate('/')}><span className="ph-brandmark">PH</span><span className="ph-brand-copy"><strong>PiHub Advisory</strong><small>Structuring workspace</small></span></button><div className="ph-workspace-context"><span className="ph-workspace-badge">Advisory</span><span className="ph-workspace-context-copy"><strong>{DEMO_DEAL.id}</strong><small>{DEMO_DEAL.name}</small></span></div></div><div className="ph-topbar-spacer"/><div className="ph-topbar-controls"><div className="ph-environment-chip" aria-label="Demo environment"><span className="ph-environment-dot"/><span className="ph-environment-copy"><strong>Demo workspace</strong><small>Local browser data · no live records</small></span></div><WorkspaceAccount user={session.user} onLogout={onLogout} onHome={()=>navigate('/')} secondaryAction={{label:'Execution tasks',onSelect:()=>navigate('/tasks')}}/></div></header><div className="ph-mobile-nav" aria-label={`${APP_LABEL} navigation`}>{items.map(link)}</div><div className="ph-shell"><aside className="ph-sidebar"><div className="ph-sidebar-primary"><Link className="ph-button primary" to="/transactions">Open transactions</Link></div>{NAV.map(s=><div className="ph-sidebar-section" key={s.label}><div className="ph-nav-label">{s.label}</div>{s.items.map(link)}</div>)}<div className="ph-sidebar-foot"><div className="ph-sidebar-foot-copy">Advisory owns mandate, structuring and execution coordination around shared deal records.</div><div className="ph-system-line"><i/><b>DEMO DATA</b><span>EUR</span></div></div></aside><main className="ph-main" key={location.pathname}><Routes><Route path="/" element={<Overview/>}/><Route path="/mandates" element={<Mandates/>}/><Route path="/transactions" element={<Transactions/>}/><Route path="/structuring" element={<Structuring/>}/><Route path="/counterparties" element={<Counterparties/>}/><Route path="/due-diligence" element={<DueDiligence/>}/><Route path="/execution" element={<Execution/>}/><Route path="/tasks" element={<Tasks/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></main></div></div>};
export default function App(){const[session]=useState(()=>consumeDemoAccessHandoff({applicationId:APP_ID,account:DEMO_ACCOUNT})||readDemoSession(APP_ID));if(!session)return <Redirect/>;return <Workspace session={session} onLogout={()=>{clearDemoSession(APP_ID);redirectToCentralAccess(APP_ID)}}/>}
