import React, { useState } from 'react';
import { DEMO_DEAL, DEMO_DOCUMENTS, DEMO_MANDATES, euro } from '../../../packages/domain/src/demo-data';
import { readLocal, writeLocal } from './local-state';
import { Card, Field, Metric, PageHead, Status } from './ui';

export const Overview = () => <><PageHead eyebrow="Advisory / Overview" title="Transaction workspace" subtitle="Manage mandates, structures, counterparties and execution milestones while keeping one canonical deal identity." action={<a className="ph-button primary" href="/transactions">Open transaction pipeline</a>}/>
<div className="ph-demo">Demo workspace. Advisory state is browser-local and does not claim production deal persistence or investor publication.</div>
<div className="ph-grid cols-4"><Metric value={DEMO_MANDATES.length} label="Active mandates"/><Metric value={euro(DEMO_MANDATES.reduce((s,m)=>s+m.amount,0))} label="Mandated volume"/><Metric value="2" label="DD workstreams due"/><Metric value="1" label="Term sheet in negotiation"/></div>
<div className="ph-grid cols-2" style={{marginTop:16}}><Card title="Priority transaction"><dl className="ph-kv"><dt>Deal</dt><dd>{DEMO_DEAL.id}</dd><dt>Client</dt><dd>{DEMO_DEAL.borrower}</dd><dt>Structure</dt><dd>{DEMO_DEAL.structure}</dd><dt>Amount</dt><dd>{euro(DEMO_DEAL.requestedAmount)}</dd><dt>Owner</dt><dd>{DEMO_DEAL.owner}</dd><dt>Next review</dt><dd>{DEMO_DEAL.nextReview}</dd></dl></Card><Card title="Execution focus"><ul className="ph-list"><li><span>Confirm lender shortlist</span><Status tone="warn">Today</Status></li><li><span>Independent valuation sign-off</span><Status tone="warn">In review</Status></li><li><span>Update sources & uses</span><Status>Open</Status></li></ul></Card></div></>;

export const Mandates = () => {
 const [items,setItems]=useState(()=>readLocal('mandates',DEMO_MANDATES));
 const change=(id,stage)=>{const next=items.map(x=>x.id===id?{...x,stage}:x);setItems(next);writeLocal('mandates',next)};
 return <><PageHead eyebrow="Advisory / Mandates" title="Mandates" subtitle="Track the client mandate, transaction type, commercial stage and next milestone without mixing this operational view into Investor navigation."/>
 <div className="ph-table-wrap"><table className="ph-table"><thead><tr><th>Mandate</th><th>Client</th><th>Transaction</th><th>Amount</th><th>Stage</th><th>Owner</th></tr></thead><tbody>{items.map(m=><tr key={m.id}><td><strong>{m.id}</strong></td><td>{m.client}</td><td>{m.transaction}<div className="ph-metric-label">{m.type}</div></td><td>{euro(m.amount)}</td><td><select aria-label={`Stage for ${m.id}`} value={m.stage} onChange={e=>change(m.id,e.target.value)}><option>Origination</option><option>Structuring</option><option>Due diligence</option><option>Term sheet</option><option>Documentation</option><option>Closed</option></select></td><td>{m.owner}</td></tr>)}</tbody></table></div></>;
};

export const Transactions = () => <><PageHead eyebrow="Advisory / Transactions" title="Transactions" subtitle="A transaction is the same underlying deal that Borrower and Investor see through their own permissions, not a copied advisory-only record."/>
<Card title={`${DEMO_DEAL.id} · ${DEMO_DEAL.name}`}><div className="ph-grid cols-4"><div><div className="ph-metric">{euro(DEMO_DEAL.requestedAmount)}</div><div className="ph-metric-label">Facility</div></div><div><div className="ph-metric">{DEMO_DEAL.ltv}%</div><div className="ph-metric-label">LTV</div></div><div><div className="ph-metric">{DEMO_DEAL.ltc}%</div><div className="ph-metric-label">LTC</div></div><div><div className="ph-metric">{DEMO_DEAL.tenorMonths}m</div><div className="ph-metric-label">Tenor</div></div></div><hr style={{border:0,borderTop:'1px solid #edf1f5',margin:'20px 0'}}/><dl className="ph-kv"><dt>Borrower</dt><dd>{DEMO_DEAL.borrower}</dd><dt>Sponsor</dt><dd>{DEMO_DEAL.sponsor}</dd><dt>Pricing</dt><dd>{DEMO_DEAL.pricing}</dd><dt>Security</dt><dd>{DEMO_DEAL.lien}</dd><dt>Stage</dt><dd><Status tone="warn">{DEMO_DEAL.status}</Status></dd></dl></Card></>;

export const Structuring = () => {
 const seed={structure:DEMO_DEAL.structure,amount:String(DEMO_DEAL.requestedAmount),pricing:DEMO_DEAL.pricing,tenor:String(DEMO_DEAL.tenorMonths),lien:DEMO_DEAL.lien,notes:'Staged drawdown, interest reserve, lender step-in rights and standard project covenants.'};
 const [form,setForm]=useState(()=>readLocal('structure',seed));const [saved,setSaved]=useState(false);const update=e=>setForm({...form,[e.target.name]:e.target.value});
 return <><PageHead eyebrow="Advisory / Structuring" title="Financing structure" subtitle="Shape the facility terms in Advisory while keeping investor-facing underwriting and borrower-facing progress separate."/><form className="ph-card ph-stack" onSubmit={e=>{e.preventDefault();writeLocal('structure',form);setSaved(true)}}><div className="ph-form-grid"><Field label="Structure"><input name="structure" value={form.structure} onChange={update}/></Field><Field label="Amount (EUR)"><input name="amount" value={form.amount} onChange={update}/></Field><Field label="Pricing"><input name="pricing" value={form.pricing} onChange={update}/></Field><Field label="Tenor (months)"><input name="tenor" value={form.tenor} onChange={update}/></Field><Field label="Security priority"><input name="lien" value={form.lien} onChange={update}/></Field></div><Field label="Structuring notes"><textarea name="notes" value={form.notes} onChange={update}/></Field><div><button className="ph-button primary">Save structure</button>{saved?<span className="ph-status good" style={{marginLeft:10}}>Saved locally</span>:null}</div></form></>;
};

export const Counterparties = () => <><PageHead eyebrow="Advisory / Parties" title="Counterparties" subtitle="Keep sponsor, borrower, lenders, advisers and service providers clear around the same transaction."/><div className="ph-grid cols-3"><Card title="Borrower"><strong>{DEMO_DEAL.borrower}</strong><p className="ph-subtitle">Primary financing applicant and facility obligor.</p></Card><Card title="Sponsor"><strong>{DEMO_DEAL.sponsor}</strong><p className="ph-subtitle">Equity sponsor and development manager.</p></Card><Card title="PiHub"><strong>PiHub Private Investments GmbH</strong><p className="ph-subtitle">Mandate owner, structuring and financing coordination.</p></Card></div></>;

export const DueDiligence = () => {
 const seed=[{id:'dd-fin',name:'Financial',owner:'Marta Klein',done:true},{id:'dd-legal',name:'Legal',owner:'External counsel',done:false},{id:'dd-tech',name:'Technical',owner:'Technical adviser',done:false},{id:'dd-val',name:'Valuation',owner:'Independent valuer',done:false},{id:'dd-kyb',name:'KYB / UBO',owner:'Compliance',done:true}];
 const [items,setItems]=useState(()=>readLocal('dd',seed));const toggle=id=>{const next=items.map(x=>x.id===id?{...x,done:!x.done}:x);setItems(next);writeLocal('dd',next)};
 return <><PageHead eyebrow="Advisory / Due diligence" title="Due diligence" subtitle="Coordinate workstreams and findings. Production DD requires document/version ownership and server audit history."/><div className="ph-table-wrap"><table className="ph-table"><thead><tr><th>Workstream</th><th>Owner</th><th>Status</th><th></th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><strong>{i.name}</strong></td><td>{i.owner}</td><td><Status tone={i.done?'good':'warn'}>{i.done?'Complete':'Open'}</Status></td><td><button className="ph-button" onClick={()=>toggle(i.id)}>{i.done?'Reopen':'Mark complete'}</button></td></tr>)}</tbody></table></div><Card title="Documents used in DD"><ul className="ph-list">{DEMO_DOCUMENTS.map(d=><li key={d.id}><span>{d.name}</span><Status tone={d.status==='Accepted'?'good':'warn'}>{d.status}</Status></li>)}</ul></Card></>;
};

export const Execution = () => <><PageHead eyebrow="Advisory / Execution" title="Term sheet & execution" subtitle="Track commercial agreement, documentation, conditions precedent and closing milestones without exposing internal notes to the Borrower module."/><div className="ph-grid cols-4"><Card title="Lender shortlist"><Status tone="good">Complete</Status><p className="ph-subtitle">Three financing providers shortlisted.</p></Card><Card title="Indicative terms"><Status tone="good">Complete</Status><p className="ph-subtitle">Pricing and leverage range aligned.</p></Card><Card title="Term sheet"><Status tone="warn">Negotiating</Status><p className="ph-subtitle">Sponsor comments due 27 Aug.</p></Card><Card title="Documentation"><Status>Not started</Status><p className="ph-subtitle">Begins after term-sheet approval.</p></Card></div></>;

export const Tasks = () => {
 const seed=[{id:'t1',title:'Issue lender shortlist memo',owner:'Marta Klein',due:'2026-08-25',done:false},{id:'t2',title:'Review valuation assumptions',owner:'Jonas Weber',due:'2026-08-26',done:false},{id:'t3',title:'Confirm sponsor equity evidence',owner:'Compliance',due:'2026-08-27',done:true}];
 const [items,setItems]=useState(()=>readLocal('tasks',seed));const toggle=id=>{const next=items.map(x=>x.id===id?{...x,done:!x.done}:x);setItems(next);writeLocal('tasks',next)};
 return <><PageHead eyebrow="Advisory / Tasks" title="Execution tasks" subtitle="Keep transaction ownership and deadlines visible instead of scattering them across email and private notes."/><div className="ph-table-wrap"><table className="ph-table"><thead><tr><th>Task</th><th>Owner</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>{items.map(t=><tr key={t.id}><td>{t.title}</td><td>{t.owner}</td><td>{t.due}</td><td><Status tone={t.done?'good':'warn'}>{t.done?'Complete':'Open'}</Status></td><td><button className="ph-button" onClick={()=>toggle(t.id)}>{t.done?'Reopen':'Complete'}</button></td></tr>)}</tbody></table></div></>;
};
