import { test, expect } from '@playwright/test';
const CENTRAL_LOGIN='https://pihub-investor.vercel.app';
const stubCentralLogin=async page=>page.route(`${CENTRAL_LOGIN}/**`,route=>route.fulfill({status:200,contentType:'text/html',body:'<!doctype html><html><body><h1>Central PiHub sign in</h1></body></html>'}));
const open=page=>page.goto('/?pihub_demo_access=advisory&source=investor-access');
const routes=[['Mandates','/mandates','Mandates'],['Transactions','/transactions',/PH-2026-0147/],['Structuring','/structuring','Financing structure'],['Counterparties','/counterparties','Counterparties'],['Due diligence','/due-diligence','Due diligence'],['Execution','/execution','Term sheet & execution'],['Tasks','/tasks','Execution tasks']];

test('advisory handoff, Investor design contract and every destination work',async({page})=>{await open(page);await expect(page.getByRole('heading',{name:'Transaction overview'})).toBeVisible();await expect(page).not.toHaveURL(/pihub_demo_access/);await expect(page.locator('.ph-app[data-workspace="advisory"]')).toBeVisible();if((page.viewportSize()?.width||0)>820){const d=await page.evaluate(()=>{const c=n=>getComputedStyle(n),r=c(document.documentElement);return{font:c(document.body).fontFamily,size:c(document.body).fontSize,top:c(document.querySelector('.ph-topbar')).height,side:c(document.querySelector('.ph-sidebar')).width,bg:c(document.querySelector('.ph-sidebar')).backgroundColor,canvas:c(document.querySelector('.ph-main')).backgroundColor,primary:r.getPropertyValue('--pi-primary').trim()}});expect(d.font).toContain('IBM Plex Sans');expect(d.size).toBe('15px');expect(d.top).toBe('68px');expect(d.side).toBe('232px');expect(d.bg).toBe('rgb(11, 18, 32)');expect(d.canvas).toBe('rgb(246, 248, 252)');expect(d.primary).toBe('#2457e6')}for(const[link,path,heading]of routes){await page.getByRole('link',{name:link,exact:true}).first().click();await expect(page).toHaveURL(new RegExp(`${path}$`));await expect(page.getByRole('heading',{name:heading})).toBeVisible()}expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(2)});

test('advisory mandate, structuring, DD and task mutations persist',async({page})=>{await open(page);await page.goto('/mandates');const stage=page.getByLabel('Stage for MAN-2417');await stage.selectOption('Term sheet');await page.reload();await expect(stage).toHaveValue('Term sheet');await page.goto('/structuring');await page.getByLabel('Pricing').fill('EURIBOR + 450 bps');await page.getByRole('button',{name:'Save structure'}).click();await page.reload();await expect(page.getByLabel('Pricing')).toHaveValue('EURIBOR + 450 bps');await page.goto('/due-diligence');await page.getByRole('button',{name:'Mark complete'}).first().click();await expect(page.getByText('Complete',{exact:true}).first()).toBeVisible();await page.goto('/tasks');await page.getByRole('button',{name:'Complete'}).first().click();await expect(page.getByText('Complete',{exact:true}).first()).toBeVisible()});

test('advisory has one login surface and sign out returns centrally',async({page})=>{await open(page);await stubCentralLogin(page);await page.getByRole('button',{name:'Sign out'}).click();await expect(page).toHaveURL(`${CENTRAL_LOGIN}/login/advisory`)});
test('advisory direct visit has no fallback login',async({page})=>{await stubCentralLogin(page);await page.goto('/');await expect(page).toHaveURL(`${CENTRAL_LOGIN}/login/advisory`);await expect(page.getByRole('button',{name:'Open Advisory'})).toHaveCount(0)});
